### PR TITLE
Apply PEP8 suggestions via autopep8

### PR DESCRIPTION
**Pull request by sanand0**
@mk-fg -- I was designing a config system and came up with a design identical to yours. Found this repo when I was searching for AttrDict implementations for YAML.

If you don't mind, I'd like to help with the maintenance of this repository -- documentation, test cases, PEP8 fixes, etc to begin with. I'd rather work with your code than maintain a separate fork.

This is a pull request to make the code mostly PEP8 compliant (via `autopep8` and a few manual edits.) Will send some test cases and doc updates over the next few days.

### CODE REVIEW

**Comment by mk-fg** [comment]
Sorry, but I don't like and don't want to follow PEP8.

As should be obvious from the code here, I kinda have my own weird and crappy style, and I've tried adopting PEP8 in the past, but all it led to is me abandoning the codebase, as it's too hard and inconvenient to work with (e.g. pulseaudio-mixer-cli projects, and some others) or refactoring back to my style (e.g. python-onedrive).

I guess many people might be fine with it though, likely the majority, so I think refactoring you did and stuff such as tests that you're planning to do is awesome and The Right Thing for a module useful for everybody, it's just that I'd rather maintain my own fork - way easier for me that way.

Furthermore, people asked for things like Python 2.6 and 3.x here a lot (iirc, check closed issues), which I'm also just "meh" about, and if you'll also be willing to implement these, I think it'll be fantastic.

------

So going forward, I think maintaining a separate pep8 and "best practices" fork is still the best option.

As I can't vouch for any fork (no offense), I'd rather not transfer PyPI project to fork that I don't know much about, as that can be unfair to any (probably super-rare) users of the project, especially if there are any significant changes planned there.

But given that the name of this project is kinda terrible anyway (as with most of my projects, blame lack of imagination), I think you can just come up with the better one and register that on PyPI instead, and I propose to link it at the top of the README with "FOR NEW PROJECTS USE THAT ONE INSTEAD" kind of message.

You can also send message to github support and they'll make your fork not to be considered such (i.e. no "forked from ..." at the top), which I think might be a good idea with a separate pypi project - to avoid confusion for new users as to which "fork" to pick, and some other upsides github-ui-wise.

Does that make any sense?

**Comment by sanand0** [comment]
That's fine @mk-fg. In that case, I'll just create a new repo derived from this, credit it, and maintain it independently.

Thanks for building this in the first place!

**Comment by mk-fg** [comment]
Thanks!
Let me know if there's something I can do to help there.

I've added a todo for adding links to the readme here, should find and link all similar modules (iirc there was at least one from beets author) when I'll get to it, including proper version of this one.

**Comment by mk-fg** [comment]
Added the Links section now (including sanand0/orderedattrdict), wonder if maybe you might find something more suitable for your use-case there as well - plenty of yaml-reading attr-access layered whatever-updating modules around, generally way better-maintained than this one ;)

**Comment by mk-fg** [comment]
Oh, right, forgot the link: https://github.com/mk-fg/layered-yaml-attrdict-config#links

**Comment by sanand0** [comment]
Thanks @mk-fg -- that list definitely helps.

**Pull request closed without merging**
